#!/bin/sh
# To prevent debug code from being accidentally committed, simply add a comment near your
# debug code containing the keyword FIXME and this script will abort the commit.
#
if git commit -v --dry-run | grep '^[+].*FIXME:' #>/dev/null 2>&1
then
  echo "Trying to commit non-committable code."
  exit 1
else
  # Run local pre-commit hook if exists
  if [ -e ./.git/hooks/pre-commit ]; then
    ./.git/hooks/pre-commit "$@"
  else
    exit 0
  fi
fi
